package com.skaidb.jdbc;

import com.skaidb.Skaidb;
import java.sql.BatchUpdateException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Deque;
import java.util.List;

/**
 * A JDBC Statement. The SQL is sent verbatim ({@code ?} is not a
 * placeholder). With a fetch size above zero a statement is STREAMED
 * ({@code OP_QUERY_STREAM}): rows arrive a chunk at a time and the
 * connection is busy until the result set is read to the end or closed.
 * Otherwise the whole result arrives in one frame.
 */
public class SkaidbStatement implements Statement {
    final SkaidbConnection conn;
    boolean closed = false;
    SkaidbResultSet current;
    long updateCount = -1;
    final Deque<SkaidbResultSet> more = new ArrayDeque<>();
    int maxRows = 0;
    int fetchSize;
    int queryTimeout = 0;
    boolean closeOnCompletion = false;
    boolean poolable = false;
    private final List<String> batch = new ArrayList<>();
    SQLWarning warnings;

    SkaidbStatement(SkaidbConnection conn) {
        this.conn = conn;
        this.fetchSize = conn.config().fetchSize;
    }

    void checkOpen() throws SQLException {
        if (closed) throw Errors.closed("statement");
        conn.checkOpen();
    }

    /** Run {@code call} against the driver, with the query timeout and error mapping applied. */
    <T> T call(java.util.function.Supplier<T> call) throws SQLException {
        Skaidb.Connection c = conn.nativeConnection();
        int before = c.getReadTimeout();
        boolean bounded = queryTimeout > 0;
        try {
            if (bounded) c.setReadTimeout(queryTimeout * 1000);
            return call.get();
        } catch (RuntimeException e) {
            throw Errors.map(e);
        } finally {
            if (bounded) {
                try {
                    c.setReadTimeout(before);
                } catch (RuntimeException ignored) {
                    // the connection is broken; it re-dials with the old timeout
                }
            }
        }
    }

    /** Close what the previous execution left and reset the result state. */
    void resetResults() throws SQLException {
        if (current != null) current.closeQuietly();
        for (SkaidbResultSet rs : more) rs.closeQuietly();
        current = null;
        more.clear();
        updateCount = -1;
    }

    /** Take a finished execution's answer. True when it produced rows. */
    boolean accept(Skaidb.Result r) throws SQLException {
        if (!r.hasRows()) {
            updateCount = r.isDdl() ? 0 : r.getAffected();
            return false;
        }
        Skaidb.ResultSet rs = r.getResultSet();
        boolean first = true;
        do {
            String[] cols = rs.getColumnNames();
            List<Object[]> rows = new ArrayList<>(rs.getRowCount());
            while (rs.next()) {
                if (maxRows > 0 && rows.size() >= maxRows) continue;
                Object[] row = new Object[cols.length];
                for (int i = 0; i < cols.length; i++) row[i] = rs.getObject(i + 1);
                rows.add(row);
            }
            SkaidbResultSet out = new SkaidbResultSet(this, cols, rows);
            if (first) current = out;
            else more.add(out);
            first = false;
        } while (rs.nextResultSet());
        return true;
    }

    boolean acceptStream(Skaidb.RowStream s) {
        if (s.getColumnNames().length == 0) {
            updateCount = Math.max(s.getAffected(), 0);
            return false;
        }
        current = new SkaidbResultSet(this, s, maxRows);
        return true;
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        checkOpen();
        resetResults();
        conn.beforeStatement();
        Skaidb.Connection c = conn.nativeConnection();
        if (fetchSize > 0) return acceptStream(call(() -> c.stream(sql)));
        return accept(call(() -> c.executeRaw(sql)));
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        if (!execute(sql)) throw new SQLException("the statement returned no result set", "02000");
        return current;
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        return (int) Math.min(Integer.MAX_VALUE, executeLargeUpdate(sql));
    }

    @Override
    public long executeLargeUpdate(String sql) throws SQLException {
        if (execute(sql)) {
            resetResults();
            throw new SQLException("the statement returned a result set; use executeQuery", "21000");
        }
        return updateCount;
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        if (autoGeneratedKeys != NO_GENERATED_KEYS) throw Errors.unsupported("generated keys (use INSERT ... RETURNING)");
        return execute(sql);
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        throw Errors.unsupported("generated keys (use INSERT ... RETURNING)");
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        throw Errors.unsupported("generated keys (use INSERT ... RETURNING)");
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        if (autoGeneratedKeys != NO_GENERATED_KEYS) throw Errors.unsupported("generated keys (use INSERT ... RETURNING)");
        return executeUpdate(sql);
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        throw Errors.unsupported("generated keys (use INSERT ... RETURNING)");
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        throw Errors.unsupported("generated keys (use INSERT ... RETURNING)");
    }

    @Override
    public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        if (autoGeneratedKeys != NO_GENERATED_KEYS) throw Errors.unsupported("generated keys (use INSERT ... RETURNING)");
        return executeLargeUpdate(sql);
    }

    @Override
    public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
        throw Errors.unsupported("generated keys (use INSERT ... RETURNING)");
    }

    @Override
    public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
        throw Errors.unsupported("generated keys (use INSERT ... RETURNING)");
    }

    /** Always empty: skaidb reports no generated keys (use {@code INSERT ... RETURNING}). */
    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        checkOpen();
        return new SkaidbResultSet(null, new String[0], new ArrayList<>());
    }

    // ---- batches ------------------------------------------------------------------

    @Override
    public void addBatch(String sql) throws SQLException {
        checkOpen();
        batch.add(sql);
    }

    @Override
    public void clearBatch() throws SQLException {
        checkOpen();
        batch.clear();
    }

    /**
     * Runs the statements one after another. Each autocommits unless a
     * transaction is open; on a failure the counts of the statements that
     * ran are in the {@link BatchUpdateException}.
     */
    @Override
    public int[] executeBatch() throws SQLException {
        long[] l = executeLargeBatch();
        int[] out = new int[l.length];
        for (int i = 0; i < l.length; i++) out[i] = (int) Math.min(Integer.MAX_VALUE, l[i]);
        return out;
    }

    @Override
    public long[] executeLargeBatch() throws SQLException {
        checkOpen();
        resetResults();
        List<String> todo = new ArrayList<>(batch);
        batch.clear();
        if (todo.isEmpty()) return new long[0];
        conn.beforeStatement();
        Skaidb.Connection c = conn.nativeConnection();
        long[] counts = new long[todo.size()];
        for (int i = 0; i < todo.size(); i++) {
            String sql = todo.get(i);
            try {
                Skaidb.Result r = call(() -> c.executeRaw(sql));
                if (r.hasRows()) throw new SQLException("batch statement " + (i + 1) + " returned a result set", "21000");
                counts[i] = r.isDdl() ? 0 : r.getAffected();
            } catch (SQLException e) {
                throw new BatchUpdateException(e.getMessage(), e.getSQLState(), e.getErrorCode(),
                    Arrays.copyOf(counts, i), e);
            }
        }
        return counts;
    }

    // ---- results ------------------------------------------------------------------

    @Override
    public ResultSet getResultSet() throws SQLException {
        checkOpen();
        return current;
    }

    @Override
    public int getUpdateCount() throws SQLException {
        return (int) Math.min(Integer.MAX_VALUE, getLargeUpdateCount());
    }

    @Override
    public long getLargeUpdateCount() throws SQLException {
        checkOpen();
        return current != null ? -1 : updateCount;
    }

    @Override
    public boolean getMoreResults() throws SQLException {
        return getMoreResults(CLOSE_CURRENT_RESULT);
    }

    /** The further result sets of a {@code CALL} whose procedure EMITs several. */
    @Override
    public boolean getMoreResults(int currentHandling) throws SQLException {
        checkOpen();
        if (currentHandling != KEEP_CURRENT_RESULT && current != null) current.closeQuietly();
        updateCount = -1;
        current = more.poll();
        return current != null;
    }

    void resultClosed(SkaidbResultSet rs) throws SQLException {
        if (closeOnCompletion && rs == current && more.isEmpty()) close();
    }

    // ---- settings -----------------------------------------------------------------

    @Override
    public int getMaxRows() throws SQLException {
        checkOpen();
        return maxRows;
    }

    @Override
    public void setMaxRows(int max) throws SQLException {
        checkOpen();
        if (max < 0) throw new SQLException("maxRows must be >= 0", "HY024");
        maxRows = max;
    }

    @Override
    public long getLargeMaxRows() throws SQLException { return getMaxRows(); }

    @Override
    public void setLargeMaxRows(long max) throws SQLException {
        setMaxRows((int) Math.min(Integer.MAX_VALUE, max));
    }

    /** 0 = unlimited; the only supported value. */
    @Override
    public int getMaxFieldSize() throws SQLException {
        checkOpen();
        return 0;
    }

    @Override
    public void setMaxFieldSize(int max) throws SQLException {
        checkOpen();
        if (max != 0) throw Errors.unsupported("a maximum field size");
    }

    /** JDBC escape syntax ({@code {fn ...}}) is not translated either way. */
    @Override
    public void setEscapeProcessing(boolean enable) throws SQLException { checkOpen(); }

    /** Seconds; a statement that exceeds it fails with SQLTimeoutException and the connection re-dials. */
    @Override
    public int getQueryTimeout() throws SQLException {
        checkOpen();
        return queryTimeout;
    }

    @Override
    public void setQueryTimeout(int seconds) throws SQLException {
        checkOpen();
        if (seconds < 0) throw new SQLException("query timeout must be >= 0", "HY024");
        queryTimeout = seconds;
    }

    @Override
    public void cancel() throws SQLException {
        throw Errors.unsupported("cancel (use setQueryTimeout)");
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        checkOpen();
        return warnings;
    }

    @Override
    public void clearWarnings() throws SQLException {
        checkOpen();
        warnings = null;
    }

    @Override
    public void setCursorName(String name) throws SQLException {
        throw Errors.unsupported("named cursors");
    }

    @Override
    public void setFetchDirection(int direction) throws SQLException {
        checkOpen();
        if (direction != ResultSet.FETCH_FORWARD) throw Errors.unsupported("fetch direction " + direction);
    }

    @Override
    public int getFetchDirection() throws SQLException {
        checkOpen();
        return ResultSet.FETCH_FORWARD;
    }

    /** Above zero: stream results (see the class comment). The value itself is not a row count: the server sizes chunks. */
    @Override
    public void setFetchSize(int rows) throws SQLException {
        checkOpen();
        if (rows < 0) throw new SQLException("fetch size must be >= 0", "HY024");
        fetchSize = rows;
    }

    @Override
    public int getFetchSize() throws SQLException {
        checkOpen();
        return fetchSize;
    }

    @Override
    public int getResultSetConcurrency() throws SQLException {
        checkOpen();
        return ResultSet.CONCUR_READ_ONLY;
    }

    @Override
    public int getResultSetType() throws SQLException {
        checkOpen();
        return ResultSet.TYPE_FORWARD_ONLY;
    }

    @Override
    public int getResultSetHoldability() throws SQLException {
        checkOpen();
        return ResultSet.HOLD_CURSORS_OVER_COMMIT;
    }

    @Override
    public Connection getConnection() throws SQLException {
        checkOpen();
        return conn;
    }

    @Override
    public void close() throws SQLException {
        if (closed) return;
        closed = true;
        resetResults();
        batch.clear();
    }

    @Override
    public boolean isClosed() { return closed; }

    @Override
    public void setPoolable(boolean poolable) throws SQLException {
        checkOpen();
        this.poolable = poolable;
    }

    @Override
    public boolean isPoolable() throws SQLException {
        checkOpen();
        return poolable;
    }

    @Override
    public void closeOnCompletion() throws SQLException {
        checkOpen();
        closeOnCompletion = true;
    }

    @Override
    public boolean isCloseOnCompletion() throws SQLException {
        checkOpen();
        return closeOnCompletion;
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        if (iface.isInstance(this)) return iface.cast(this);
        throw new SQLException("not a wrapper for " + iface.getName(), "HY000");
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) { return iface.isInstance(this); }
}
